services:
  console:
    container_name: ${CONTAINER_NAME}
    networks:
      1panel-network:
    ports:
      - "${DIRECTUS_ADMIN_PORT}:8055"
    image: directus/directus:11.3.5
    volumes:
      - ./extensions:/directus/extensions
    environment:
      - KEY=${DIRECTUS_KEY}
      - SECRET=${DIRECTUS_SECRET}
      - DB_CLIENT=pg
      - DB_HOST=${DIRECTUS_DB_HOST}
      - DB_PORT=${DIRECTUS_DB_PORT}
      - DB_DATABASE=${DIRECTUS_DB_NAME}
      - DB_USER=${DIRECTUS_DB_USER}
      - DB_PASSWORD=${DIRECTUS_DB_USER_PASSWORD}
      - CACHE_ENABLED=true
      - CACHE_AUTO_PURGE=true
      - CACHE_STORE=redis
      - REDIS="redis://default:${DIRECTUS_REDIS_ROOT_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}"
      - ADMIN_EMAIL=${DIRECTUS_EMAIL}
      - ADMIN_PASSWORD=${DIRECTUS_PASSWORD}
      - STORAGE_LOCATIONS=${STORAGE_LOCATION}
      - STORAGE_S3_DRIVER=s3
      - STORAGE_S3_KEY=${STORAGE_S3_KEY}
      - STORAGE_S3_SECRET=${STORAGE_S3_SECRET}
      - STORAGE_S3_BUCKET=${STORAGE_S3_BUCKET}
      - STORAGE_S3_REGION=${STORAGE_S3_REGION}
      - STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
