services:
  console:
    container_name: ${CONTAINER_NAME}
    networks:
      1panel-network:
    ports:
      - "${PANEL_ADMIN_PORT}:8000"
    image: miaosi/miaosi-admin:0.0.1
    volumes:
      - ./ConfigCenter:/app/ConfigCenter
      - ./upload/:/app/wwwroot/upload
      - ./nlogs/:/nlogs
      - ./appsettings.json:/app/appsettings.json
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
